me: AsynchchronousGillz
markdown: kramdown

relative_permalinks: false
title: AsynchronousGillz
repository: https://github.com/AsynchronousGillz/AsynchronousGillz.github.io
timezone: America/Denver
baseurl: ""

permalink: /blog/:year/:month/:day/:title

collections:
  books:
    - subtitle
    - author
    - amazon
    - published
    - read
    - pages
    - ISBN

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "posts"
    values:
      layout: "posts"
