me: AsynchchronousGillz
markdown: kramdown

relative_permalinks: false
title: AsynchronousGillz
repository: https://github.com/AsynchronousGillz/AsynchronousGillz.github.io
timezone: America/Denver
baseurl: ""

permalink: /blog/:year/:month/:day/:title

collections:
  books:
    subtitle: "title"
    author: "author"
    amazon: "link to amazon"
    published: "published year"
    read: "date I read it"
    pages: "number of pages"
    ISBN: "ISBN number"

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "posts"
    values:
      layout: "posts"
